# Generated by Django 4.1.2 on 2022-10-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_remove_especialidad_usuario_creacion_and_more'),
        ('seguridad', '0002_alter_usuario_is_active_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.profesor', unique=True),
        ),
    ]
