# Generated by Django 4.1.2 on 2022-10-30 14:33

from django.db import migrations, models
import modulos.persona.validators


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_departamento_genero_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='celular',
            field=models.IntegerField(default=0, validators=[modulos.persona.validators.validar_celular], verbose_name='Nro. Celular'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/tutor/', verbose_name='Fotografía del Tutor(a)'),
        ),
    ]
