# Generated by Django 4.1.2 on 2022-10-30 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modulos.persona.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0006_remove_estudiante_calleavenida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='documento',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='expedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.departamento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/estudiante/', verbose_name='Fotografía del Tutor(a)'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('documento', models.CharField(max_length=15, unique=True, verbose_name='Carnet de Identidad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno')),
                ('fotografia', models.ImageField(blank=True, max_length=200, null=True, upload_to='media/profesor/', verbose_name='Fotografía del Tutor(a)')),
                ('celular', models.IntegerField(default=0, validators=[modulos.persona.validators.validar_celular], verbose_name='Nro. Celular')),
                ('especialidad', models.ManyToManyField(to='persona.especialidad')),
                ('expedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.departamento')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.genero')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
