# Generated by Django 4.1.2 on 2022-11-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_remove_especialidad_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/estudiante/', verbose_name='Fotografía del Estudiante'),
        ),
    ]
