# Generated by Django 4.1.2 on 2022-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_alter_estudiante_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateTimeField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fotografia',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/profesor/', verbose_name='Fotografía del Profesor(a)'),
        ),
    ]
