# Generated by Django 4.1.2 on 2022-12-07 21:50

from django.db import migrations, models
import modulos.persona.validators


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_alter_estudiante_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.IntegerField(default=0, max_length=8, validators=[modulos.persona.validators.validar_celular], verbose_name='Nro. Celular'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
