# Generated by Django 4.1.2 on 2022-12-07 22:01

from django.db import migrations, models
import modulos.persona.validators


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_alter_estudiante_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.IntegerField(default=0, validators=[modulos.persona.validators.validar_celular], verbose_name='Nro. Celular'),
        ),
    ]
