# Generated by Django 4.1.2 on 2023-01-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametro', '0006_alter_dia_dia_tipoestudiante'),
        ('persona', '0012_alter_estudiante_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha de Asistencia')),
                ('hora_llegada', models.DateTimeField(verbose_name='Hora de Llegada')),
                ('hora_salida', models.DateTimeField(verbose_name='Hora de Salida')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.estudiante')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kardex.asistencia')),
                ('indicador_positivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametro.indicador')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametro.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='persona.profesor')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia con Detalle',
                'verbose_name_plural': 'Asistencias con Detalles',
            },
        ),
        migrations.CreateModel(
            name='DetalleIndicadoresNegativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('asistenciadetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kardex.asistenciadetalle')),
                ('indicador_negativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametro.indicador')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia con Detalle e Indicador negativo',
                'verbose_name_plural': 'Asistencias con Detalles e Indicadores negativos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaIndicadoresNegativosGral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='kardex.asistencia')),
                ('indicador_negativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametro.indicador')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_eliminacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia con Indicador Negativo General',
                'verbose_name_plural': 'Asistencias con Indicadores Negativos Generales',
            },
        ),
    ]
