# Generated by Django 4.1.2 on 2023-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_llegada',
            field=models.TimeField(verbose_name='Hora de Llegada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(verbose_name='Hora de Salida'),
        ),
    ]
