# Generated by Django 4.1.2 on 2023-01-28 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_alter_dia_dia_tipoestudiante'),
        ('kardex', '0002_alter_asistencia_hora_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadetalle',
            name='indicador_positivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='parametro.indicador'),
        ),
    ]
